<<<<<<< Updated upstream
# Generated by Django 3.2.4 on 2021-07-22 07:24

from django.db import migrations, models
=======
# Generated by Django 3.2.4 on 2021-07-22 06:55

from django.db import migrations, models
import django.utils.timezone
>>>>>>> Stashed changes


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='color',
<<<<<<< Updated upstream
            field=models.CharField(default='black', max_length=32),
=======
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
>>>>>>> Stashed changes
            preserve_default=False,
        ),
    ]
