# Generated by Django 3.2.4 on 2021-07-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='color',
            field=models.CharField(default='black', max_length=32),
            preserve_default=False,
        ),
    ]
