# Generated by Django 3.2.5 on 2021-08-02 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomorder',
            name='shipping_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='total_net_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roomorder',
            name='undiscounted_total_net_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='userorderline',
            unique_together={('user', 'product')},
        ),
    ]
