# Generated by Django 3.2.4 on 2021-07-30 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webtraffic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitehit',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_hits', to='webtraffic.website'),
        ),
    ]
